import { Injectable, signal } from '@angular/core';

export type Lang = 'EN' | 'FR';

@Injectable({
    providedIn: 'root'
})
export class LanguageService {
    private lang = signal<Lang>('EN');

    private translations: Record<Lang, Record<string, string>> = {
        'EN': {
            'NAV_DASHBOARD': 'Dashboard',
            'NAV_CHECKLIST': 'Checklist',
            'NAV_USERS': 'Users',
            'NAV_LOGOUT': 'Logout',
            'MEMBER_MGMT': 'Member Management',
            'CREATE_USER': 'Create New User',
            'EDIT_USER': 'Edit User',
            'SYSTEM_USERS': 'System Users',
            'FULL_NAME': 'Full Name',
            'EMAIL_ADDR': 'Email Address',
            'PASSWORD': 'Password',
            'USER_ROLE': 'User Role',
            'NAME': 'Name',
            'EMAIL': 'Email',
            'ROLE': 'Role',
            'CREATED': 'Created',
            'ACTIONS': 'Actions',
            'CANCEL': 'Cancel',
            'UPDATE': 'Update',
            'CREATE': 'Create',
            'SEARCH_PLACEHOLDER': 'Global search...',
            'ADMIN': 'Administrator',
            'DEVELOPER': 'Developer',
            'AUDITOR': 'Auditor',
            'LOGIN_TITLE': 'Sign In',
            'LOGIN_SUB': 'Enter your credentials to access ASVS',
            'LOGIN_BTN': 'Sign In',
            'LOGIN_LOADING': 'Signing in...',
            'EMAIL_ERROR': 'Invalid email or password',
            'GUEST': 'Guest',
            'OR': 'OR',
            'DASH_TITLE': 'OWASP ASVS Dashboard',
            'DASH_SUB': 'Overview of security compliance status',
            'MY_PROJECTS': 'My Projects',
            'MY_COMPLIANCE': 'My Compliance',
            'MY_STATS': 'My Statistics',
            'GLOBAL_COMPLIANCE': 'Global Compliance',
            'PROJECTS_STATUS': 'Projects Status',
            'TOTAL_REQS': 'Total Requirements',
            'APPLICABLE_REQS': 'Applicable Requirements',
            'PASS': 'Pass',
            'FAIL': 'Fail',
            'NA': 'N/A',
            'UNREVIEWED': 'Unreviewed',
            'COMPLIANCE_BY_CAT': 'Compliance by Category',
            'EXPORT_PDF': 'Export PDF',
            'NEW_PROJECT': 'New Project',
            'CREATE_PROJ': 'Project Name',
            'LOADING': 'Loading...',
            'CATEGORY': 'Category',
            'COMPLIANCE': 'Compliance',
            'DONE': 'Done',
            'IN_PROGRESS': 'In Progress',
            'NOT_DONE': 'Not Done',
            'NOT_APPLICABLE': 'Not Applicable',
            'UNTESTED': 'Untested',
            'BACK': 'Back',
            'SEARCH_REQS': 'Search requirements...',
            'ALL_AREAS': 'All Areas',
            'LEVEL_ALL': 'All Levels',
            'LEVEL_1': 'Level 1',
            'LEVEL_2': 'Level 2',
            'LEVEL_3': 'Level 3',
            'EXPORT_EXCEL': 'Export Excel',
            'SAVE': 'Save',
            'SAVING': 'Saving...',
            'EVIDENCE': 'Evidence & Comments',
            'TOOLS': 'Tools used',
            'REFERENCES': 'Source code references',
            'AI_SUGGESTION': 'AI Suggestion',
            'APPLY_AI': 'Apply to Evidence',
            'COPY': 'Copy',
            'COPIED': 'Copied!',
            'AI_SUMMARY': 'Summary',
            'AI_WHAT_TO_DO': 'Steps to verify',
            'AI_CODE': 'Example Code / Reference',
            'AI_FILES': 'Relevant Files',
            'USER_CREATED_SUCCESS': 'User created successfully! ✅',
            'USER_UPDATED_SUCCESS': 'User updated successfully! ✅',
            'USER_DELETED_SUCCESS': 'User deleted successfully! ✅',
            'DELETE_CONFIRM': 'Are you sure you want to delete this user? This action cannot be undone.',
            'LOADING_USERS_FAIL': 'Failed to load users',
            'LEAVE_BLANK_HINT': 'Leave blank to keep current',
            'MEMBERS': 'Members',
            'PROJECT_MEMBERS': 'Project Members',
            'ADD_MEMBER': 'Add Member',
            'REMOVE_MEMBER': 'Remove Member',
            'SEARCH_USERS': 'Search users...',
            'NO_USERS_FOUND': 'No users found',
            'ALREADY_MEMBER': 'Already a member',
            'ADD': 'Add',
            'REMOVE': 'Remove',
            'REMOVING': 'Removing...',
            'Architecture': 'Architecture',
            'Authentication': 'Authentication',
            'Session Management': 'Session Management',
            'Access Control': 'Access Control',
            'Input Validation': 'Input Validation',
            'Cryptography at Rest': 'Cryptography at Rest',
            'Error Handling and Logging': 'Error Handling and Logging',
            'Data Protection': 'Data Protection',
            'Communication Security': 'Communication Security',
            'Malicious Code': 'Malicious Code',
            'Business Logic': 'Business Logic',
            'Files and Resources': 'Files and Resources',
            'API and Web Service': 'API and Web Service',
            'Configuration': 'Configuration',
            'USER_ROLE_HINT': 'Account type',
            'PROJECT_DETAILS': 'Project Details',
            'PROJECT_OVERVIEW': 'Project Overview',
            'DEV_MESSAGES': 'Developer Messages',
            'DEVELOPER_MESSAGES': 'Developer Messages',
            'MESSAGES_SUBTITLE': 'Review notes sent by developers across all projects',
            'LOADING_MESSAGES': 'Loading developer notes...',
            'NO_MESSAGES': 'No messages found',
            'NO_MESSAGES_DESC': 'Developers haven\'t left any notes for administrators yet.',
            'VIEW_IN_CHECKLIST': 'View in Checklist',
            'REMARQUE_ADMIN': 'Admin Remark',
            'DEVELOPER_NOTE': 'Developer Note',
            'ADMIN_RESPONSE': 'Admin Response',
            'EVIDENCE_PREVIEW': 'Evidence Preview'
        },
        'FR': {
            'NAV_DASHBOARD': 'Tableau de bord',
            'NAV_CHECKLIST': 'Checklist',
            'NAV_USERS': 'Utilisateurs',
            'NAV_LOGOUT': 'Déconnexion',
            'MEMBER_MGMT': 'Gestion des membres',
            'CREATE_USER': 'Créer un utilisateur',
            'EDIT_USER': 'Modifier l\'utilisateur',
            'SYSTEM_USERS': 'Utilisateurs système',
            'FULL_NAME': 'Nom complet',
            'EMAIL_ADDR': 'Email',
            'PASSWORD': 'Mot de passe',
            'USER_ROLE': 'Rôle',
            'NAME': 'Nom',
            'EMAIL': 'Email',
            'ROLE': 'Rôle',
            'CREATED': 'Créé le',
            'ACTIONS': 'Actions',
            'CANCEL': 'Annuler',
            'UPDATE': 'Mettre à jour',
            'CREATE': 'Créer',
            'SEARCH_PLACEHOLDER': 'Recherche globale...',
            'ADMIN': 'Administrateur',
            'DEVELOPER': 'Développeur',
            'AUDITOR': 'Auditeur',
            'LOGIN_TITLE': 'Connexion',
            'LOGIN_SUB': 'Entrez vos identifiants pour accéder à ASVS',
            'LOGIN_BTN': 'Se connecter',
            'LOGIN_LOADING': 'Connexion...',
            'EMAIL_ERROR': 'Email ou mot de passe incorrect',
            'GUEST': 'Invité',
            'OR': 'OU',
            'DASH_TITLE': 'Tableau de Bord OWASP ASVS',
            'DASH_SUB': 'Aperçu de l\'état de conformité sécurité',
            'MY_PROJECTS': 'Mes Projets',
            'MY_COMPLIANCE': 'Ma Conformité',
            'MY_STATS': 'Mes Statistiques',
            'GLOBAL_COMPLIANCE': 'Conformité globale',
            'PROJECTS_STATUS': 'État des projets',
            'TOTAL_REQS': 'Exigences totales',
            'APPLICABLE_REQS': 'Exigences applicables',
            'PASS': 'Réussi',
            'FAIL': 'Échoué',
            'NA': 'N/A',
            'UNREVIEWED': 'Non revu',
            'COMPLIANCE_BY_CAT': 'Conformité par catégorie',
            'EXPORT_PDF': 'Exporter PDF',
            'NEW_PROJECT': 'Nouveau projet',
            'CREATE_PROJ': 'Nom du projet',
            'LOADING': 'Chargement...',
            'CATEGORY': 'Catégorie',
            'COMPLIANCE': 'Conformité',
            'DONE': 'Terminé',
            'IN_PROGRESS': 'En cours',
            'NOT_DONE': 'Non fait',
            'NOT_APPLICABLE': 'Non applicable',
            'UNTESTED': 'Non testé',
            'BACK': 'Retour',
            'SEARCH_REQS': 'Rechercher des exigences...',
            'ALL_AREAS': 'Toutes les zones',
            'LEVEL_ALL': 'Tous les niveaux',
            'LEVEL_1': 'Niveau 1',
            'LEVEL_2': 'Niveau 2',
            'LEVEL_3': 'Niveau 3',
            'EXPORT_EXCEL': 'Exporter Excel',
            'SAVE': 'Enregistrer',
            'SAVING': 'Enregistrement...',
            'EVIDENCE': 'Preuves & Commentaires',
            'TOOLS': 'Outils utilisés',
            'REFERENCES': 'Références code source',
            'AI_SUGGESTION': 'Suggestion IA',
            'APPLY_AI': 'Appliquer aux preuves',
            'COPY': 'Copier',
            'COPIED': 'Copié !',
            'AI_SUMMARY': 'Résumé',
            'AI_WHAT_TO_DO': 'Étapes à vérifier',
            'AI_CODE': 'Exemple de code / Référence',
            'AI_FILES': 'Fichiers pertinents',
            'USER_CREATED_SUCCESS': 'Utilisateur créé avec succès ! ✅',
            'USER_UPDATED_SUCCESS': 'Utilisateur mis à jour avec succès ! ✅',
            'USER_DELETED_SUCCESS': 'Utilisateur supprimé avec succès ! ✅',
            'DELETE_CONFIRM': 'Êtes-vous sûr de vouloir supprimer cet utilisateur ? Cette action est irréversible.',
            'LOADING_USERS_FAIL': 'Échec du chargement des utilisateurs',
            'LEAVE_BLANK_HINT': 'Laissez vide pour conserver l\'actuel',
            'MEMBERS': 'Membres',
            'PROJECT_MEMBERS': 'Membres du projet',
            'ADD_MEMBER': 'Ajouter un membre',
            'REMOVE_MEMBER': 'Retirer le membre',
            'SEARCH_USERS': 'Rechercher des utilisateurs...',
            'NO_USERS_FOUND': 'Aucun utilisateur trouvé',
            'ALREADY_MEMBER': 'Déjà membre',
            'ADD': 'Ajouter',
            'REMOVE': 'Retirer',
            'REMOVING': 'Retrait...',
            'Architecture': 'Architecture',
            'Authentication': 'Authentification',
            'Session Management': 'Gestion de session',
            'Access Control': 'Contrôle d\'accès',
            'Input Validation': 'Validation des entrées',
            'Cryptography at Rest': 'Cryptographie au repos',
            'Error Handling and Logging': 'Gestion des erreurs et journalisation',
            'Data Protection': 'Protection des données',
            'Communication Security': 'Sécurité des communications',
            'Malicious Code': 'Code malveillant',
            'Business Logic': 'Logique métier',
            'Files and Resources': 'Fichiers et ressources',
            'API and Web Service': 'API et service Web',
            'Configuration': 'Configuration',
            'USER_ROLE_HINT': 'Type de compte',
            'PROJECT_DETAILS': 'Détails du projet',
            'PROJECT_OVERVIEW': 'Aperçu du projet',
            'DEV_MESSAGES': 'Messages des Développeurs',
            'DEVELOPER_MESSAGES': 'Messages des Développeurs',
            'MESSAGES_SUBTITLE': 'Consultez les notes envoyées par les développeurs sur tous les projets',
            'LOADING_MESSAGES': 'Chargement des notes des développeurs...',
            'NO_MESSAGES': 'Aucun message trouvé',
            'NO_MESSAGES_DESC': 'Les développeurs n\'ont pas encore laissé de notes pour les administrateurs.',
            'VIEW_IN_CHECKLIST': 'Voir dans la checklist',
            'REMARQUE_ADMIN': 'Remarque pour Admin',
            'DEVELOPER_NOTE': 'Note du Développeur',
            'ADMIN_RESPONSE': 'Réponse de l\'Admin',
            'EVIDENCE_PREVIEW': 'Aperçu des preuves'
        }
    };

    constructor() {
        const saved = localStorage.getItem('lang') as Lang;
        if (saved && (saved === 'EN' || saved === 'FR')) {
            this.lang.set(saved);
        }
    }

    get currentLang() {
        return this.lang();
    }

    setLang(newLang: Lang) {
        this.lang.set(newLang);
        localStorage.setItem('lang', newLang);
    }

    translate(key: string): string {
        return this.translations[this.lang()][key] || key;
    }
}
